<h2><?= $message ?></h2> <!--Informations sur la BDD -->

<p id="paragDescription">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam fringilla, ante eu commodo malesuada, arcu erat pellentesque dui, sed scelerisque ex velit ornare tellus. Donec tincidunt pulvinar consectetur. Maecenas ac justo lorem. Praesent rhoncus mi eget nibh egestas tincidunt. Etiam scelerisque ex justo, eu commodo massa tincidunt ut. Aenean eu justo in magna porta luctus non nec ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec accumsan nibh. Aenean pulvinar odio sit amet lobortis auctor. In efficitur lacus in mauris sagittis semper. Quisque dignissim risus nec tincidunt auctor.
    <br>
    Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tristique, tellus a lobortis efficitur, leo ex elementum neque, non hendrerit lacus lorem a quam. Vestibulum ut vehicula libero. Donec sagittis vulputate nibh a placerat. Etiam elementum lobortis risus, id accumsan ipsum sodales a. Ut posuere sit amet dui in congue. Nam est dui, rutrum et dolor in, convallis pellentesque massa. Nunc in rutrum sapien.
    <br>
    Suspendisse et mattis risus. Nullam tincidunt felis vitae urna molestie, et interdum leo consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam et leo eu nisl tincidunt molestie. Fusce orci enim, vehicula eu ligula at, tincidunt blandit diam. Sed at hendrerit tortor, sed euismod lectus. Maecenas id risus est. Curabitur libero lacus, rhoncus id tellus mollis, ullamcorper pretium odio.
    <br>
    Duis eget rutrum erat. Suspendisse aliquet massa luctus, posuere eros nec, vulputate augue. Etiam in semper justo. Ut quis nisl lacus. Ut porta posuere bibendum. Nullam quis metus sed tellus tincidunt pharetra non at magna. Suspendisse accumsan diam eget lacus mattis faucibus in nec turpis. Ut consectetur aliquam eros non suscipit. Praesent dictum nec erat a interdum. In ullamcorper sem nec arcu mattis imperdiet. Phasellus nec aliquam ex. Phasellus scelerisque est ut suscipit venenatis.
    <br>
    Praesent scelerisque nisi ante, a ultricies augue fermentum id. Maecenas id convallis elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus dui in tortor congue congue. In gravida vel leo feugiat placerat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam et purus dolor. Integer blandit eros ante, nec imperdiet leo sagittis non. Quisque ultricies et turpis eu pharetra. Maecenas mi quam, elementum in molestie sit amet, luctus sed sapien. Fusce cursus vitae massa a fermentum. Praesent ut arcu convallis, consectetur diam consequat, ultrices augue. Donec tristique magna nunc, vitae cursus mauris commodo quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer fermentum libero sapien, quis convallis mi molestie at.
</p>